apiVersion: v1
kind: Template
metadata:
  name: fmi-api
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: fmi-api
    name: fmi-api
  spec:
    replicas: 10
    selector:
      app: fmi-api
      deploymentconfig: fmi-api
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: fmi-api
          deploymentconfig: fmi-api
      spec:
        containers:
        - image: docker-url:prod
          imagePullPolicy: Always
          name: fmi-api
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 1500m
              memory: 4G
            requests:
              cpu: 1
              memory: 3G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: JAVA_OPTS
              value: "-Xms3500M -Xmx3500M"
            - name: ENVIRONMENT_NAME
              value: prod
            - name: AES_KEY
              valueFrom:
                secretKeyRef:
                  key: password
                  name: prod-aes-key-secure-1
            - name: TG_AES_KEY
              valueFrom:
                secretKeyRef:
                  key: password
                  name: prod-aes-key-tg-1
            - name: KEYSTORE_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: prod-key-store-password-1
            - name: TRUSTSTORE_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: prod-trust-store-password-1
            - name: SHOW_LOGS
              value: 'false'
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app: fmi-api
    name: application-service
  spec:
    ports:
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: fmi-api
      deploymentconfig: fmi-api
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/path: /actuator/prometheus
      prometheus.io/port: '8080'
      prometheus.io/scheme: http
      prometheus.io/scrape: 'true'
    labels:
      app: fmi-api
    name: management-service
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: fmi-api
      deploymentconfig: fmi-api
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/balance: roundrobin
      openshift.io/host.generated: 'true'
    labels:
      app: fmi-api
    name: fmi-api
    namespace: prod-c360-fmi-api
    selfLink: /oapi/v1/namespaces/prod-c360-fmi-api/routes/fmi-api
  spec:
    host: namespace.host
    port:
      targetPort: 8443-tcp
    to:
      kind: Service
      name: application-service
      weight: 100
    tls:
      termination: passthrough
    wildcardPolicy: None

- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/balance: roundrobin
      openshift.io/host.generated: 'true'
    labels:
      app: fmi-api
    name: proj.domain
    namespace: prod-c360-fmi-api
    selfLink: /oapi/v1/namespaces/prod-c360-project/domain
  spec:
    host: project.domain
    port:
      targetPort: 8443-tcp
    to:
      kind: Service
      name: application-service
      weight: 100
    tls:
      termination: passthrough
    wildcardPolicy: None
