apiVersion: v1
kind: Template
metadata:
  name: my-retail-api
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: my-retail-api
    name: my-retail-api
  spec:
    replicas: 10
    selector:
      app: my-retail-api
      deploymentconfig: my-retail-api
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: my-retail-api
          deploymentconfig: my-retail-api
      spec:
        containers:
        - image: docker.domain.com/namespace/my-retail-api:prod
          imagePullPolicy: Always
          name: my-retail-api
          ports:
          - containerPort: 8444
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 3G
            requests:
              cpu: 1
              memory: 2G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: JAVA_OPTS
              value: "-Xms2500M -Xmx2500M"
            - name: ENVIRONMENT_NAME
              value: prod
            - name: AES_KEY
              valueFrom:
                secretKeyRef:
                  key: password
                  name: prod-aes-key-secure-1
            - name: KEYSTORE_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: prod-key-store-password-1
            - name: TRUSTSTORE_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: prod-trust-store-password-1
            - name: SHOW_LOGS
              value: 'false'
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app: my-retail-api
    name: application-service
  spec:
    ports:
    - name: 8444-tcp
      port: 8444
      protocol: TCP
      targetPort: 8444
    selector:
      app: my-retail-api
      deploymentconfig: my-retail-api
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/path: /actuator/prometheus
      prometheus.io/port: '8080'
      prometheus.io/scheme: http
      prometheus.io/scrape: 'true'
    labels:
      app: my-retail-api
    name: management-service
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: my-retail-api
      deploymentconfig: my-retail-api
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/balance: roundrobin
      openshift.io/host.generated: 'true'
    labels:
      app: my-retail-api
    name: my-retail-api
    namespace: prod-my-retail-api
    selfLink: /oapi/v1/namespaces/prod-my-retail-api/routes/my-retail-api
  spec:
    host: my-retail-api-prod-all.origin.domain.com
    port:
      targetPort: 8444-tcp
    to:
      kind: Service
      name: application-service
      weight: 100
    tls:
      termination: passthrough
    wildcardPolicy: None

- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/balance: roundrobin
      openshift.io/host.generated: 'true'
    labels:
      app: my-retail-api
    name: my-retail-api.domain.com
    namespace: prod-my-retail-api
    selfLink: /oapi/v1/namespaces/prod-my-retail-api/routes/my-retail-api.domain.com
  spec:
    host: my-retail-api.domain.com
    port:
      targetPort: 8444-tcp
    to:
      kind: Service
      name: application-service
      weight: 100
    tls:
      termination: passthrough
    wildcardPolicy: None
