/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.company.org.model.avro.product;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CurrentPrice extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5290868537857174165L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CurrentPrice\",\"namespace\":\"com.company.org.model.avro.product\",\"fields\":[{\"name\":\"value\",\"type\":\"double\"},{\"name\":\"currency_code\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"USD\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CurrentPrice> ENCODER =
      new BinaryMessageEncoder<CurrentPrice>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CurrentPrice> DECODER =
      new BinaryMessageDecoder<CurrentPrice>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<CurrentPrice> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<CurrentPrice> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CurrentPrice>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this CurrentPrice to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a CurrentPrice from a ByteBuffer. */
  public static CurrentPrice fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private double value;
   private String currency_code;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CurrentPrice() {}

  /**
   * All-args constructor.
   * @param value The new value for value
   * @param currency_code The new value for currency_code
   */
  public CurrentPrice(Double value, String currency_code) {
    this.value = value;
    this.currency_code = currency_code;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return value;
    case 1: return currency_code;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: value = (Double)value$; break;
    case 1: currency_code = (String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public Double getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(Double value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'currency_code' field.
   * @return The value of the 'currency_code' field.
   */
  public String getCurrencyCode() {
    return currency_code;
  }

  /**
   * Sets the value of the 'currency_code' field.
   * @param value the value to set.
   */
  public void setCurrencyCode(String value) {
    this.currency_code = value;
  }

  /**
   * Creates a new CurrentPrice RecordBuilder.
   * @return A new CurrentPrice RecordBuilder
   */
  public static com.company.org.model.avro.product.CurrentPrice.Builder newBuilder() {
    return new com.company.org.model.avro.product.CurrentPrice.Builder();
  }

  /**
   * Creates a new CurrentPrice RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CurrentPrice RecordBuilder
   */
  public static com.company.org.model.avro.product.CurrentPrice.Builder newBuilder(com.company.org.model.avro.product.CurrentPrice.Builder other) {
    return new com.company.org.model.avro.product.CurrentPrice.Builder(other);
  }

  /**
   * Creates a new CurrentPrice RecordBuilder by copying an existing CurrentPrice instance.
   * @param other The existing instance to copy.
   * @return A new CurrentPrice RecordBuilder
   */
  public static com.company.org.model.avro.product.CurrentPrice.Builder newBuilder(com.company.org.model.avro.product.CurrentPrice other) {
    return new com.company.org.model.avro.product.CurrentPrice.Builder(other);
  }

  /**
   * RecordBuilder for CurrentPrice instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CurrentPrice>
    implements org.apache.avro.data.RecordBuilder<CurrentPrice> {

    private double value;
    private String currency_code;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.company.org.model.avro.product.CurrentPrice.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.currency_code)) {
        this.currency_code = data().deepCopy(fields()[1].schema(), other.currency_code);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing CurrentPrice instance
     * @param other The existing instance to copy.
     */
    private Builder(com.company.org.model.avro.product.CurrentPrice other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.currency_code)) {
        this.currency_code = data().deepCopy(fields()[1].schema(), other.currency_code);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public Double getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.company.org.model.avro.product.CurrentPrice.Builder setValue(double value) {
      validate(fields()[0], value);
      this.value = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public com.company.org.model.avro.product.CurrentPrice.Builder clearValue() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'currency_code' field.
      * @return The value.
      */
    public String getCurrencyCode() {
      return currency_code;
    }

    /**
      * Sets the value of the 'currency_code' field.
      * @param value The value of 'currency_code'.
      * @return This builder.
      */
    public com.company.org.model.avro.product.CurrentPrice.Builder setCurrencyCode(String value) {
      validate(fields()[1], value);
      this.currency_code = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'currency_code' field has been set.
      * @return True if the 'currency_code' field has been set, false otherwise.
      */
    public boolean hasCurrencyCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'currency_code' field.
      * @return This builder.
      */
    public com.company.org.model.avro.product.CurrentPrice.Builder clearCurrencyCode() {
      currency_code = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CurrentPrice build() {
      try {
        CurrentPrice record = new CurrentPrice();
        record.value = fieldSetFlags()[0] ? this.value : (Double) defaultValue(fields()[0]);
        record.currency_code = fieldSetFlags()[1] ? this.currency_code : (String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CurrentPrice>
    WRITER$ = (org.apache.avro.io.DatumWriter<CurrentPrice>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CurrentPrice>
    READER$ = (org.apache.avro.io.DatumReader<CurrentPrice>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
